export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const TOAST_SHOW = 'TOAST_SHOW';
export const DASHBOARD ='DASHBOARD';
export const HOME_REDIRECT='HOME_REDIRECT';

export const SALES_PAGE_LOADED = 'SALES_PAGE_LOADED';
export const SALES_PAGE_UNLOADED = 'SALES_PAGE_UNLOADED';
export const UPDATE_FIELD_SALES = 'UPDATE_FIELD_SALES'
export const ADD_SALES='ADD_SALES';
export const UPDATE_USER_SALES='UPDATE_USER_SALES';
export const SALES_FORM_CLEAR='SALES_FORM_CLEAR';
export const DELETE_SALES_USER='DELETE_SALES_USER';

export const SALESMAN_LIST ='SALESMAN_LIST';
export const SALESMAN_ITEM_CLICK ='SALESMAN_ITEM_CLICK';
export const SALESMAN_DETAIL ='SALESMAN_DETAIL';
export const SALESMAN_VIEW_DETAIL ='SALESMAN_VIEW_DETAIL';
export const SALES_GET_DETAIL ='SALES_GET_DETAIL';
export const SALES_EDIT_DETAIL ='SALES_EDIT_DETAIL';
export const SALES_UPDATE_DETAIL ='SALES_UPDATE_DETAIL';
export const SALES_APPOINTMENT_ASSIGN ='SALES_APPOINTMENT_ASSIGN';
export const SALES_APPOINTMENT_CANCEL ='SALES_APPOINTMENT_CANCEL';
export const SALES_APPOINTMENT_RESCHEDULE ='SALES_APPOINTMENT_RESCHEDULE';
export const SALES_USERS_FILTER ='SALES_USERS_FILTER';

export const MAKEIT_USRE_PAGE_LOADED = 'MAKEIT_USRE_PAGE_LOADED';
export const MAKEIT_USRE_PAGE_UNLOADED = 'MAKEIT_USRE_PAGE_UNLOADED';
export const MAKEIT_UPDATE_FIELD= 'MAKEIT_UPDATE_FIELD'
export const MAKEIT_UPDATE_FIELD_MULTIPLE= 'MAKEIT_UPDATE_FIELD_MULTIPLE'
export const MAKEIT_UPDATE_MENU_IMAGES= 'MAKEIT_UPDATE_MENU_IMAGES'
export const MAKEIT_DELETE_MENU_IMAGES= 'MAKEIT_DELETE_MENU_IMAGES'
export const MAKEIT_ADD_USER='MAKEIT_ADD_USER';
export const MAKEIT_UPDATE_USER='MAKEIT_UPDATE_USER';
export const MAKEIT_FORM_CLEAR='MAKEIT_FORM_CLEAR';
export const MAKEIT_DELETE_USER='MAKEIT_DELETE_USER';
export const MAKEIT_VIEW_DETAIL='MAKEIT_VIEW_DETAIL';
export const MAKEIT_USERS_LIST ='MAKEIT_USERS_LIST';
export const MAKEIT_USERS_FILTER ='MAKEIT_USERS_FILTER';
export const MAKEIT_USERS_SERVICE='MAKEIT_USERS_SERVICE';
export const MAKEIT_USERS_DELETE='MAKEIT_USERS_DELETE';
export const MAKEIT_USER_DETAIL='MAKEIT_USER_DETAIL';
export const MAKEIT_GET_REGION='MAKEIT_GET_REGION';
export const MAKEIT_GET_CUISINE='MAKEIT_GET_CUISINE';
export const MAKEIT_GET_CLUSTER='MAKEIT_GET_CLUSTER';
export const MAKEIT_GET_HOMETOWN='MAKEIT_GET_HOMETOWN';
export const MAKEIT_GET_HUB='MAKEIT_GET_HUB';
export const MAKEIT_GET_HUB_SELEDED='MAKEIT_GET_HUB_SELEDED';
export const MAKEIT_UNAPPROVED_USERS_LIST ='MAKEIT_UNAPPROVED_USERS_LIST';
export const MAKEIT_UNAPPROVED__USERS_FILTER ='MAKEIT_UNAPPROVED__USERS_FILTER';
export const MAKEIT_ZONE_AREA='MAKEIT_ZONE_AREA';
export const MAKEIT_GET_PRODUCT_TAG='MAKEIT_GET_PRODUCT_TAG';

export const MAKEIT_SUBMENU_SELECT ='MAKEIT_SUBMENU_SELECT';

export const MAKEIT_PRODUCT_PAGE_LOAD ='MAKEIT_PRODUCT_PAGE_LOAD';
export const MAKEIT_PRODUCT_PAGE_UNLOAD ='MAKEIT_PRODUCT_PAGE_UNLOAD';
export const MAKEIT_PRODUCT_ADD ='MAKEIT_PRODUCT_ADD';
export const MAKEIT_PRODUCT_ITEM_ADD ='MAKEIT_PRODUCT_ITEM_ADD';
export const MAKEIT_PRODUCT_ITEM_REMOVE ='MAKEIT_PRODUCT_ITEM_REMOVE';
export const MAKEIT_PRODUCT_ITEM_UP ='MAKEIT_PRODUCT_ITEM_UP';
export const MAKEIT_PRODUCT_ITEM_DOWN ='MAKEIT_PRODUCT_ITEM_DOWN';
export const MAKEIT_PRODUCT_IMAGE ='MAKEIT_PRODUCT_IMAGE';
export const MAKEIT_PRODUCT_IMAGE_PRE_LOAD ='MAKEIT_PRODUCT_IMAGE_PRE_LOAD';
export const MAKEIT_PRODUCT_LOAD ='MAKEIT_PRODUCT_LOAD';
export const MAKEIT_PRODUCT_CLEAR ='MAKEIT_PRODUCT_CLEAR';
export const MAKEIT_PRODUCT_FORM_CLEAR ='MAKEIT_PRODUCT_FORM_CLEAR';
export const MAKEIT_PRODUCT_FORM_LOAD ='MAKEIT_PRODUCT_FORM_LOAD';
export const MAKEIT_PRODUCT_MENU ='MAKEIT_PRODUCT_MENU';
export const KITCHEN_PRODUCT_PERCENTAGE ='KITCHEN_PRODUCT_PERCENTAGE';
export const MAKEIT_PRODUCT_LIVE ='MAKEIT_PRODUCT_LIVE';
export const MAKEIT_PRODUCT_GET_LIVE ='MAKEIT_PRODUCT_GET_LIVE';
export const MAKEIT_ADD_ITEMS_ALL ='MAKEIT_ADD_ITEMS_ALL';
export const MAKEIT_PRODUCT_ITEMS_LIST ='MAKEIT_PRODUCT_ITEMS_LIST';
export const MAKEIT_PRODUCT_MOVE_LIVE ='MAKEIT_PRODUCT_MOVE_LIVE';
export const MAKEIT_PRODUCT_MENU_DELETE ='MAKEIT_PRODUCT_MENU_DELETE';
export const MAKEIT_PRODUCT_DELETE_CLEAR ='MAKEIT_PRODUCT_DELETE_CLEAR';
export const VIRTUAL_PRODUCT_LIST='VIRTUAL_PRODUCT_LIST';
export const VIRTUAL_PRODUCT_FILTER='VIRTUAL_PRODUCT_FILTER';
export const EDIT_QUANTITY_VIRTUAL_PRODUCT_LIST='EDIT_QUANTITY_VIRTUAL_PRODUCT_LIST';
export const EDIT_QUANTITY_BUTTON_ENABLE='EDIT_QUANTITY_BUTTON_ENABLE';

export const MAKEIT_PACKAGE_ITEM_ADD ='MAKEIT_PACKAGE_ITEM_ADD';
export const MAKEIT_PACKAGE_ITEM_REMOVE='MAKEIT_PACKAGE_ITEM_REMOVE';
export const MAKEIT_PACKAGE_ITEM_COUNT_UP ='MAKEIT_PACKAGE_ITEM_COUNT_UP';
export const MAKEIT_PACKAGE_ITEM_COUNT_DOWN ='MAKEIT_PACKAGE_ITEM_COUNT_DOWN';
export const MAKEIT_PACKAGE_ITEMS_ADD_ALL ='MAKEIT_PACKAGE_ITEMS_ADD_ALL';

export const MAKEIT_PRODUCT_UNAPPROVED_LIST ='MAKEIT_PRODUCT_UNAPPROVED_LIST';
export const MAKEIT_UNAPPROVED_FILTER ='MAKEIT_UNAPPROVED_FILTER';
export const MAKEIT_PRODUCT_APPROVED_DETAIL='MAKEIT_PRODUCT_APPROVED_DETAIL';
export const MAKEIT_PRODUCT_APPROVED_UPDTAE='MAKEIT_PRODUCT_APPROVED_UPDTAE';
export const MAKEIT_ITEM_APPROVED_UPDTAE='MAKEIT_ITEM_APPROVED_UPDTAE';


export const MAKEIT_PRODUCT_DEAIL_LOAD ='MAKEIT_PRODUCT_DEAIL_LOAD';
export const MAKEIT_PRODUCT_DEAIL_ADD_LIVE ='MAKEIT_PRODUCT_DEAIL_ADD_LIVE';
export const MAKEIT_PRODUCT_DEAIL_REMOVE_LIVE ='MAKEIT_PRODUCT_DEAIL_REMOVE_LIVE';
export const MAKEIT_PRODUCT_DEAIL_CLEAR ='MAKEIT_PRODUCT_DEAIL_CLEAR';
export const MAKEIT_PRODUCT_DEAIL_EDIT_COUNT ='MAKEIT_PRODUCT_DEAIL_EDIT_COUNT';



export const MAKEIT_ITEM_POPUP_LOAD ='MAKEIT_ITEM_POPUP_LOAD';
export const MAKEIT_ITEM_POPUP_UNLOAD ='MAKEIT_ITEM_POPUP_LOAD';
export const MAKEIT_ITEM_ADD ='MAKEIT_ITEM_ADD';
export const MAKEIT_ITEM_LOAD ='MAKEIT_ITEM_LOAD';
export const MAKEIT_ITEM_CLEAR ='MAKEIT_ITEM_CLEAR';
export const MAKEIT_ITEM_LIST ='MAKEIT_ITEM_LIST';

export const MAKEIT_PACKAGE_INVENTORY_LIST ='MAKEIT_PACKAGE_INVENTORY_LIST';
export const MAKEIT_PACKAGE_INVENTORY_ROOT_LIST ='MAKEIT_PACKAGE_INVENTORY_ROOT_LIST';
export const MAKEIT_PACKAGE_INVENTORY_ROOT_LIST_FILTER ='MAKEIT_PACKAGE_INVENTORY_ROOT_LIST_FILTER';
export const MAKEIT_PACKAGE_INVENTORY_ADD ='MAKEIT_PACKAGE_INVENTORY_ADD';
export const MAKEIT_PACKAGE_INVENTORY_EDIT ='MAKEIT_PACKAGE_INVENTORY_EDIT';
export const MAKEIT_PACKAGE_INVENTORY_CLEAR ='MAKEIT_PACKAGE_INVENTORY_CLEAR';
export const MAKEIT_PACKAGE_BOX_LIST ='MAKEIT_PACKAGE_BOX_LIST';
export const PACKAGE_GET_ALL_MAKEIT_LIST ='PACKAGE_GET_ALL_MAKEIT_LIST';
export const PACKAGE_GET_SINGLE_INVENTORY ='PACKAGE_GET_SINGLE_INVENTORY';
export const MAKEIT_PACKAGE_BOX_FILTER='MAKEIT_PACKAGE_BOX_FILTER';

export const DUNZO_COD_ORDERS_ALL_LIST='DUNZO_COD_ORDERS_ALL_LIST';
export const DUNZO_COD_ORDERS_FILTER_LIST='DUNZO_COD_ORDERS_FILTER_LIST';
export const DUNZO_ORDERS_ASSIGN='DUNZO_ORDERS_ASSIGN';
export const MOVEIT_USRE_PAGE_LOADED = 'MOVEIT_USRE_PAGE_LOADED';
export const MOVEIT_USRE_PAGE_UNLOADED = 'MOVEIT_USRE_PAGE_UNLOADED';
export const MOVEIT_ADD_USER='MOVEIT_ADD_USER';
export const MOVEIT_UPDATE_FIELD='MOVEIT_UPDATE_FIELD';
export const MOVEIT_UPDATE_IMAGE_FIELD='MOVEIT_UPDATE_IMAGE_FIELD';
export const MOVEIT_CLEAR_IMAGE_FIELD='MOVEIT_CLEAR_IMAGE_FIELD';
export const MOVEIT_FORM_CLEAR='MOVEIT_FORM_CLEAR';
export const MOVEIT_DELETE_USER='MOVEIT_DELETE_USER';
export const MOVEIT_VIEW_DETAIL='MOVEIT_VIEW_DETAIL';
export const MOVEIT_USER_DETAIL='MOVEIT_USER_DETAIL';
export const MOVEIT_USERS_LIST='MOVEIT_USERS_LIST';
export const MOVEIT_LIST ='MOVEIT_LIST';
export const MOVEIT_ITEM_CLICK ='MOVEIT_ITEM_CLICK';
export const MOVEIT_ORDERS_ASSIGN ='MOVEIT_ORDERS_ASSIGN';
export const MOVEIT_ORDERS_UN_ASSIGN ='MOVEIT_ORDERS_UN_ASSIGN';
export const ORDERS_MOVETO_DUNZO ='ORDERS_MOVETO_DUNZO';
export const MOVEIT_USERS_FILTER ='MOVEIT_USERS_FILTER';
export const MOVEIT_COD_LIST ='MOVEIT_COD_LIST';
export const MOVEIT_CURRENT_LOCATION ='MOVEIT_CURRENT_LOCATION';
export const MOVEIT_CURRENT_LOCATION_CLEAR ='MOVEIT_CURRENT_LOCATION_CLEAR';

export const LIVE_GET_MAKEIT ='LIVE_GET_MAKEIT';
export const MAKEIT_LOCATION_CLEAR='MAKEIT_LOCATION_CLEAR';

export const GET_ALL_ZONE ='GET_ALL_ZONE';
export const GET_ALL_ZONE_FOR_DRAWING ='GET_ALL_ZONE_FOR_DRAWING';
export const GET_UNASSIGN_ZONE ='GET_UNASSIGN_ZONE';
export const UPDATE_ZONE_BOUNDARIES ='UPDATE_ZONE_BOUNDARIES';
export const DELETE_ZONE_BOUNDARIES ='DELETE_ZONE_BOUNDARIES';
export const ZONE_UPDATE_CLEAR ='ZONE_UPDATE_CLEAR';
export const ADD_ZONE ='ADD_ZONE';
export const ZONE_XFACTOR_LIST ='ZONE_XFACTOR_LIST';
export const ZONE_XFACTOR_UPDATE ='ZONE_XFACTOR_UPDATE';
export const ZONE_XFACTOR_UPDATE_CLEAR ='ZONE_XFACTOR_UPDATE_CLEAR';

export const MOVEIT_FORCE_LOGOUT='MOVEIT_FORCE_LOGOUT';

export const EAT_USRE_PAGE_LOADED = 'EAT_USRE_PAGE_LOADED';
export const EAT_USRE_PAGE_UNLOADED = 'EAT_USRE_PAGE_UNLOADED';
export const EAT_UPDATE_FIELD= 'EAT_UPDATE_FIELD'
export const EAT_ADD_USER='EAT_ADD_USER';
export const EAT_UPDATE_USER='EAT_UPDATE_USER';
export const EAT_FORM_CLEAR='EAT_FORM_CLEAR';
export const EAT_DELETE_USER='EAT_DELETE_USER';
export const EAT_USERS_LIST='EAT_USERS_LIST';
export const EAT_VIEW_DETAIL='EAT_VIEW_DETAIL';
export const EAT_USERS_FILTER_APPLY='EAT_USERS_FILTER_APPLY';
export const EAT_COUPON_LIST='EAT_COUPON_LIST';

export const EAT_REFUND_ORDER_LIST='EAT_REFUND_ORDER_LIST';
export const REPAYMENT='REPAYMENT';
export const PAYMENT_CLEAR='PAYMENT_CLEAR';


export const APPOINTMENT_LIST ='APPOINTMENT_LIST';
export const APPOINTMENT_ITEM_CLICK ='APPOINTMENT_ITEM_CLICK';
export const APPOINTMENT_LIST_FILTER='APPOINTMENT_LIST_FILTER';
export const APPOINTMENT_LIST_SET_FILTER='APPOINTMENT_LIST_SET_FILTER';

export const ORDERS_LIST ='ORDERS_LIST';
export const ORDERS_ITEM_CLICK ='ORDERS_ITEM_CLICK';
export const ORDERS_TABS_CLICK ='ORDERS_TABS_CLICK';

export const LIVE_PRODUCT_PAGE_LOADED='LIVE_PRODUCT_PAGE_LOADED';
export const LIVE_PRODUCT_PAGE_UNLOADED='LIVE_PRODUCT_PAGE_UNLOADED';
export const LIVE_PRODUCT_LIST='LIVE_PRODUCT_LIST';
export const LIVE_PRODUCT_FILTER_LIST='LIVE_PRODUCT_FILTER_LIST';
export const LIVE_PRODUCT_ADD_CART='LIVE_PRODUCT_ADD_CART';
export const LIVE_PRODUCT_REMOVE_CART='LIVE_PRODUCT_REMOVE_CART';
export const LIVE_ITEM_QUANTITY_UP='LIVE_ITEM_QUANTITY_UP';
export const LIVE_ITEM_QUANTITY_DOWN='LIVE_ITEM_QUANTITY_DOWN';
export const LIVE_ITEM_QUANTITY_CHECK='LIVE_ITEM_QUANTITY_CHECK';
export const LIVE_GET_RESTAURANTS='LIVE_GET_RESTAURANTS';
export const LIVE_RESTAURANTS_FILTER='LIVE_RESTAURANTS_FILTER';
export const LIVE_RESTAURANTS_SELECT='LIVE_RESTAURANTS_SELECT';
export const LIVE_RESTAURANTS_APPROVAL='LIVE_RESTAURANTS_APPROVAL';
export const LIVE_PRODUCT_RESET_CART='LIVE_PRODUCT_RESET_CART';


export const CART_TIEM_STORE ='CART_TIEM_STORE';

export const CHECKOUT_PAGE_LOADED ='CHECKOUT_PAGE_LOADED';
export const CHECKOUT_PAGE_UNLOADED='CHECKOUT_PAGE_UNLOADED';
export const CHECKOUT_USERS_LIST ='CHECKOUT_USERS_LIST';
export const CHECKOUT_USERS_SELECTED ='CHECKOUT_USERS_SELECTED';
export const CHECKOUT_USERS_PLACE ='CHECKOUT_USERS_PLACE';
export const CHECKOUT_ORDER_POST='CHECKOUT_ORDER_POST';
export const CHECKOUT_ORDER_SUCCESS='CHECKOUT_ORDER_SUCCESS';

export const ORDERS_QUEUE_LIST='ORDERS_QUEUE_LIST';
export const ORDERS_QUEUE_HUB='ORDERS_QUEUE_HUB';
export const ORDERS_QUEUE_ZONE='ORDERS_QUEUE_ZONE';
export const ORDERS_QUEUE_FILTER_ZONE='ORDERS_QUEUE_FILTER_ZONE';
export const ORDERS_QUEUE_FILTER_HUB='ORDERS_QUEUE_FILTER_HUB';

export const DUNZO_ORDERS_ALL_LIST='DUNZO_ORDERS_ALL_LIST';
export const DUNZO_ORDERS_FILTER_LIST='DUNZO_ORDERS_FILTER_LIST';
export const ORDERS_ALL_LIST='ORDERS_ALL_LIST';
export const ORDERS_FILTER_LIST='ORDERS_FILTER_LIST';
export const ORDERS_STATUS_FILTER_LIST='ORDERS_STATUS_FILTER_LIST';
export const ORDERS_PAGE_ONLOAD='ORDERS_PAGE_ONLOAD';
export const ORDER_VIEW_DETAIL='ORDER_VIEW_DETAIL';
export const ORDER_VIEW_QUALITY='ORDER_VIEW_QUALITY';
export const ORDER_STATUS_UPDATE='ORDER_STATUS_UPDATE';
export const ORDER_STATUS_CANCEL='ORDER_STATUS_CANCEL';
export const ORDER_STATUS_PREPARED_CANCEL='ORDER_STATUS_PREPARED_CANCEL';
export const ORDER_STATUS_PICKEDUP_CANCEL='ORDER_STATUS_PICKEDUP_CANCEL';
export const ORDER_ITEM_MISSING='ORDER_ITEM_MISSING';
export const ORDER_CALL_NEXT_API='ORDER_CALL_NEXT_API';
export const ORDER_UNACCPETED_LIST ='ORDER_UNACCPETED_LIST';
export const ORDERS_COD_ONLINE_LIST ='ORDERS_COD_ONLINE_LIST';
export const ORDERS_PRODUCT_COUNT ='ORDERS_PRODUCT_COUNT';
export const ORDER_DELIVED_BY_ADMIN='ORDER_DELIVED_BY_ADMIN';
export const ORDER_PAYMENT_SUCCESS='ORDER_PAYMENT_SUCCESS';
export const ORDER_CREATE_TICKET='ORDER_CREATE_TICKET';
export const GET_ZENDESK_ISSUES='GET_ZENDESK_ISSUES';

export const REPORTS_CLEAR ='REPORTS_CLEAR';
export const ORDERS_MOVEIT_REPORT ='ORDERS_MOVEIT_REPORT';
export const ORDERS_TURNORUND_REPORT_MAKEIT ='ORDERS_TURNORUND_REPORT_MAKEIT';
export const ORDERS_TURNORUND_REPORT_MOVEIT ='ORDERS_TURNORUND_REPORT_MOVEIT';
export const ORDERS_CANCELED_REPORT ='ORDERS_CANCELED_REPORT';
export const REAL_KITCHEN_ORDERS_CANCELED_REPORT ='REAL_KITCHEN_ORDERS_CANCELED_REPORT';
export const ORDERS_COST_REPORT ='ORDERS_COST_REPORT';
export const ORDERS_DELIVERED_VIA_ADMIN_REPORT ='ORDERS_DELIVERED_VIA_ADMIN_REPORT';

export const NEW_USERS_REPORT ='NEW_USERS_REPORT';
export const NEW_USERS_ORDER_REPORT ='NEW_USERS_ORDER_REPORT';
export const RETAINED_CUSTOMER_REPORT ='RETAINED_CUSTOMER_REPORT';
export const USER_ORDER_HISTORY_REPORT ='USER_ORDER_HISTORY_REPORT';

export const TOTAL_ORDERS_REPORT ='TOTAL_ORDERS_REPORT';
export const TOTAL_VIRTUAL_ORDERS_REPORT ='TOTAL_VIRTUAL_ORDERS_REPORT';
export const TOTAL_ORIGINAL_ORDERS_REPORT ='TOTAL_ORIGINAL_ORDERS_REPORT';


export const DRIVER_COD_REPORT ='DRIVER_COD_REPORT';
export const VIRTUAL_ORDERS_PURCHASED ='VIRTUAL_ORDERS_PURCHASED'
export const LOST_CUSTOMER_REPORT ='LOST_CUSTOMER_REPORT'
export const FUNNEL_ORDERED_REPORT ='FUNNEL_ORDERED_REPORT'
export const XFACTOR_ORDERED_REPORT ='XFACTOR_ORDERED_REPORT'
export const USER_GROWTH_REPORT ='USER_GROWTH_REPORT'

export const LIVE_PRODUCT_HISTORY_REPORT='LIVE_PRODUCT_HISTORY_REPORT'
export const MAKEIT_TIME_LOG_REPORT='MAKEIT_TIME_LOG_REPORT'
export const MOVEIT_TIME_LOG_REPORT='MOVEIT_TIME_LOG_REPORT'

export const ACCOUNT_REPORTS_ONLINE ='ACCOUNT_REPORTS_ONLINE';
export const ACCOUNT_REPORTS_CASH ='ACCOUNT_REPORTS_CASH';

export const KITCHEN_WISE_REPORT ='KITCHEN_WISE_REPORT';
export const VIRTUAL_KITCHEN_WISE_REPORT ='VIRTUAL_KITCHEN_WISE_REPORT';
export const ORIGINAL_KITCHEN_WISE_REPORT ='ORIGINAL_KITCHEN_WISE_REPORT';

export const PRODUCT_REPORT ='PRODUCT_REPORT';
export const VIRTUAL_PRODUCT_WISE_REPORT ='VIRTUAL_PRODUCT_WISE_REPORT';
export const ORIGINAL_PRODUCT_WISE_REPORT ='ORIGINAL_PRODUCT_WISE_REPORT';
export const VIRTUAL_KITCHEN_PREPARED_AFTER_CANCEL_REPORT ='VIRTUAL_KITCHEN_PREPARED_AFTER_CANCEL_REPORT';
export const ORIGINAL_KITCHEN_PREPARED_AFTER_CANCEL_REPORT ='ORIGINAL_KITCHEN_PREPARED_AFTER_CANCEL_REPORT';
export const VIRTUAL_KITCHEN_PREPARED_BEFORE_CANCEL_REPORT ='VIRTUAL_KITCHEN_PREPARED_BEFORE_CANCEL_REPORT';
export const ORIGINAL_KITCHEN_PREPARED_BEFORE_CANCEL_REPORT ='ORIGINAL_KITCHEN_PREPARED_BEFORE_CANCEL_REPORT';
export const VIRTUAL_KITCHEN_SUCCESSIONRATE_REPORT ='VIRTUAL_KITCHEN_SUCCESSIONRATE_REPORT';
export const REAL_KITCHEN_SUCCESSIONRATE_REPORT ='REAL_KITCHEN_SUCCESSIONRATE_REPORT';
export const MOVEIT_ORDERS_DELIVERY ='MOVEIT_ORDERS_DELIVERY';
export const MILE_MOVEIT_ORDERS_DELIVERY ='MILE_MOVEIT_ORDERS_DELIVERY';
export const MILE_MOVEIT_AVERAGE_DELIVERY ='MILE_MOVEIT_AVERAGE_DELIVERY';
export const ONLINE_REFUNDED_ORDERS ='ONLINE_REFUNDED_ORDERS';
export const COUPON_USED_ORDERS ='COUPON_USED_ORDERS';

export const ORDERS_DEATIL_REPORT_FINANCIAL ='ORDERS_DEATIL_REPORT_FINANCIAL';
export const ITEM_WISE_REPORT_FINANCIAL ='ITEM_WISE_REPORT_FINANCIAL';
export const MOVEIT_MASTER_REPORT_FINANCIAL ='MOVEIT_MASTER_REPORT_FINANCIAL';
export const MAKEIT_MASTER_REPORT_FINANCIAL ='MAKEIT_MASTER_REPORT_FINANCIAL';

export const CANCELLED_ORDERS_FOLLOW_UP ='CANCELLED_ORDERS_FOLLOW_UP';
export const UNCLOSED_ORDERS ='UNCLOSED_ORDERS';
export const CUSTOMER_EXPERIENCE='CUSTOMER_EXPERIENCE';
export const ZONE_LEVEL_PERFORMANCE='ZONE_LEVEL_PERFORMANCE';

export const QUERIES_PAGE_LOAD ='QUERIES_PAGE_LOAD';
export const QUERIES_PAGE_USER_SELECT ='QUERIES_PAGE_USER_SELECT';
export const QUERIES_QUESTIONS_LIST ='QUERIES_QUESTIONS_LIST';
export const QUERIES_SELETED_QUESTIONS ='QUERIES_SELETED_QUESTIONS';
export const QUERIES_READ ='QUERIES_READ';
export const QUERIES_REPLIES_LIST ='QUERIES_REPLIES_LIST';
export const QUERIES_REPLIES ='QUERIES_REPLIES';
export const QUERIES_CLEAR='QUERIES_CLEAR';
export const QUERIES_READ_CLEAR='QUERIES_READ_CLEAR';
export const QUERIES_USER_DETAIL ='QUERIES_USER_DETAIL';

export const QUERIES_USER_PAGE_LOAD ='QUERIES_USER_PAGE_LOAD';
export const QUERIES_USER_LIST ='QUERIES_USER_LIST';
export const QUERIES_SELETED_USER ='QUERIES_SELETED_USER';


export const FAQ_PAGE_LOAD ='FAQ_PAGE_LOAD';
export const FAQ_PAGE_USER_SELECT ='FAQ_PAGE_USER_SELECT';
export const FAQ_LIST ='FAQ_LIST';
export const FAQ_SELETED ='FAQ_SELETED';
export const FAQ_POST ='FAQ_POST';
export const FAQ_CLEAR='FAQ_CLEAR';
export const FAQ_DELETE ='FAQ_DELETE';

export const FEEDBACK_GET_ALL ='FEEDBACK_GET_ALL';
export const ORDER_RATING_GET_ALL ='ORDER_RATING_GET_ALL';
export const ORDER_RATING_SET_FILTER ='ORDER_RATING_SET_FILTER';
export const ORDER_RATING_PAGE_LOAD ='ORDER_RATING_PAGE_LOAD';
export const FEEDBACK_PAGE_LOAD ='FEEDBACK_PAGE_LOAD';
export const ADMIN_EAT_ADDRESS='ADMIN_EAT_ADDRESS';

export const MOBILE_OTP_SEND='MOBILE_OTP_SEND';
export const MOBILE_OTP_VERIFY='MOBILE_OTP_VERIFY';
export const MOBILE_OTP_CLEAR='MOBILE_OTP_CLEAR';

export const STORIES_CREATE='STORIES_CREATE';
export const STORIES_CREATE_PAGE_LOAD='STORIES_CREATE_PAGE_LOAD';
export const STORIES_CREATE_PAGE_UNLOAD='STORIES_CREATE_PAGE_UNLOAD';
export const STORIES_FORM_CLEAR='STORIES_FORM_CLEAR';
export const STORIES_FIELD_UPDATE='STORIES_FIELD_UPDATE';
export const STORIES_IMAGE_UPLOAD='STORIES_IMAGE_UPLOAD';


export const CURRENT_SELECTION_SIDE_NAV='CURRENT_SELECTION_SIDE_NAV';

export const PACKAGE_BOX_LIST='PACKAGE_BOX_LIST';
export const PACKAGE_BOX_LIST_MAP_PRODUCT='PACKAGE_BOX_LIST_MAP_PRODUCT';
export const PACKAGE_SINGLE_BOX_DETAIL='PACKAGE_SINGLE_BOX_DETAIL';
export const PACKAGE_BOX_ADD='PACKAGE_BOX_ADD';
export const PACKAGE_BOX_EDIT='PACKAGE_BOX_EDIT';
export const PACKAGE_BOX_FROM_CLEAR='PACKAGE_BOX_FROM_CLEAR';


export const PACKAGE_STOCK_LIST ='PACKAGE_STOCK_LIST';
export const PACKAGE_STOCK_LIST_FILTER ='PACKAGE_STOCK_LIST_FILTER';
export const PACKAGE_STOCK_ALERT_LIST ='PACKAGE_STOCK_ALERT_LIST';
export const PACKAGE_STOCK_LIST_ALERT_FILTER ='PACKAGE_STOCK_LIST_ALERT_FILTER';

export const PUSH_NOTIFICATION_USER_LIST ='PUSH_NOTIFICATION_USER_LIST';
export const PUSH_NOTIFICATION_USER_LIST_FILTER ='PUSH_NOTIFICATION_USER_LIST_FILTER';
export const PUSH_NOTIFICATION_SEND ='PUSH_NOTIFICATION_SEND';
export const PUSH_NOTIFICATION_CLEAR='PUSH_NOTIFICATION_CLEAR';

